version: '3.1'

services:
  mongo-db:
    image: mongo
    restart: always
  minikube-fullstack-server:
    image: minikube-fullstack-server
    restart: always
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017/organizer
  