apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-fullstack
  namespace: default
spec:
  selector:
    matchLabels:
      app: minikube-fullstack-server
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-fullstack-server
    spec:
      containers:
      - name: mongo-db
        image: mongo:latest
        ports:
        - containerPort: 27017
      - name: minikube-fullstack-server
        image: ogcamplin/minikube-fullstack-server
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: minikube-fullstack-server-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: minikube-fullstack-server
  ports:
  - port: 8080
    targetPort: 8080


